-- ===================================================
-- MedSage Clinic - Supabase Database Schema
-- Run this script in the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/acsmzastgryhkvjulipc/sql
-- ===================================================

-- 1. Create Appointments & Inquiries Table
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()),
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    service TEXT,
    message TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled'))
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

-- 3. Policy: Allow public / anonymous visitors to submit appointments
DROP POLICY IF EXISTS "Allow public appointment submissions" ON public.appointments;
CREATE POLICY "Allow public appointment submissions"
ON public.appointments
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 4. Policy: Allow reading appointments
DROP POLICY IF EXISTS "Allow reading appointments" ON public.appointments;
CREATE POLICY "Allow reading appointments"
ON public.appointments
FOR SELECT
TO anon, authenticated
USING (true);

-- 5. Optional Newsletter / Subscribers Table
CREATE TABLE IF NOT EXISTS public.subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()),
    email TEXT UNIQUE NOT NULL
);

ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public newsletter subscriptions" ON public.subscribers;
CREATE POLICY "Allow public newsletter subscriptions"
ON public.subscribers
FOR INSERT
TO anon, authenticated
WITH CHECK (true);
