-- ====================================================================
-- MedSage Clinic — Complete Supabase Database Schema
-- Includes:
-- 1. Profiles (Patient & Single-Admin Role System)
-- 2. Single-Admin Database Constraint & Trigger (Prevents Duplicate Admins)
-- 3. Appointments Management
-- 4. Medical Records & Checkup History (Vitals, Prescriptions, Follow-ups)
-- 5. Row Level Security (RLS) Policies
-- 6. One-Time Master Admin Creation Script (admin@medsageclinic.com)
-- 7. Automatic Patient Profile Trigger on Sign-up
-- 8. Sample Seed Data for Instant Demonstration
-- ====================================================================

-- Enable cryptographic functions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ====================================================================
-- 1. PROFILES TABLE (Patients & Master Admin)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT,
    role TEXT NOT NULL DEFAULT 'patient' CHECK (role IN ('admin', 'patient')),
    age INTEGER,
    gender TEXT CHECK (gender IN ('Male', 'Female', 'Other')),
    blood_group TEXT CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    allergies TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- ====================================================================
-- 2. STRICT ONE-TIME ADMIN PROTECTION
-- Enforces that ONLY ONE master admin account can exist in the system.
-- No one can create another admin account via SQL, API, or sign-up.
-- ====================================================================

-- 2.1 Unique partial index: PostgreSQL will reject any second row with role='admin'
CREATE UNIQUE INDEX IF NOT EXISTS single_admin_idx 
ON public.profiles (role) 
WHERE role = 'admin';

-- 2.2 Trigger function to double-enforce single admin policy with a descriptive error
CREATE OR REPLACE FUNCTION public.check_single_admin()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.role = 'admin' THEN
        IF EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE role = 'admin' AND id <> NEW.id
        ) THEN
            RAISE EXCEPTION 'Security Policy Violation: MedSage Clinic only allows one master administrator. Additional admin accounts cannot be created.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_prevent_multiple_admins ON public.profiles;
CREATE TRIGGER trg_prevent_multiple_admins
BEFORE INSERT OR UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.check_single_admin();

-- ====================================================================
-- 3. APPOINTMENTS TABLE
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    service TEXT,
    appointment_date DATE DEFAULT CURRENT_DATE,
    appointment_time TEXT DEFAULT '11:00 AM',
    message TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')),
    doctor_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- ====================================================================
-- 4. CHECKUPS & MEDICAL RECORDS TABLE
-- Stores full medical history, diagnoses, vitals, and prescriptions
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.checkups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    appointment_id BIGINT REFERENCES public.appointments(id) ON DELETE SET NULL,
    doctor_name TEXT DEFAULT 'Dr. Ahmad Khan',
    checkup_date DATE DEFAULT CURRENT_DATE,
    diagnosis TEXT NOT NULL,
    symptoms TEXT,
    vitals JSONB DEFAULT '{"bp": "120/80", "pulse": "72", "temp": "98.6°F", "weight": "70kg"}'::jsonb,
    prescriptions JSONB DEFAULT '[]'::jsonb,
    doctor_notes TEXT,
    follow_up_date DATE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc', NOW())
);

-- ====================================================================
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- ====================================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.checkups ENABLE ROW LEVEL SECURITY;

-- Helper function to check if current user is admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5.1 Profiles Policies
DROP POLICY IF EXISTS "Public profiles read access" ON public.profiles;
CREATE POLICY "Public profiles read access"
ON public.profiles FOR SELECT
TO authenticated
USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "Users can update own non-admin profile" ON public.profiles;
CREATE POLICY "Users can update own non-admin profile"
ON public.profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id AND role = 'patient');

DROP POLICY IF EXISTS "Admin full access to profiles" ON public.profiles;
CREATE POLICY "Admin full access to profiles"
ON public.profiles FOR ALL
TO authenticated
USING (public.is_admin());

-- 5.2 Appointments Policies
DROP POLICY IF EXISTS "Public and users can insert appointments" ON public.appointments;
CREATE POLICY "Public and users can insert appointments"
ON public.appointments FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Patients can view own appointments" ON public.appointments;
CREATE POLICY "Patients can view own appointments"
ON public.appointments FOR SELECT
TO authenticated
USING (
    patient_id = auth.uid() 
    OR email = (SELECT email FROM auth.users WHERE id = auth.uid()) 
    OR public.is_admin()
);

DROP POLICY IF EXISTS "Admin manage all appointments" ON public.appointments;
CREATE POLICY "Admin manage all appointments"
ON public.appointments FOR ALL
TO authenticated
USING (public.is_admin());

-- 5.3 Checkups Policies
DROP POLICY IF EXISTS "Patients can view own checkup records" ON public.checkups;
CREATE POLICY "Patients can view own checkup records"
ON public.checkups FOR SELECT
TO authenticated
USING (patient_id = auth.uid() OR public.is_admin());

DROP POLICY IF EXISTS "Admin manage all checkups" ON public.checkups;
CREATE POLICY "Admin manage all checkups"
ON public.checkups FOR ALL
TO authenticated
USING (public.is_admin());

-- ====================================================================
-- 6. AUTOMATIC PATIENT PROFILE TRIGGER ON AUTH SIGN-UP
-- When a user registers via patient portal, their profile is created automatically.
-- Role is always locked to 'patient'.
-- ====================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (
        id,
        email,
        full_name,
        phone,
        role,
        age,
        gender,
        blood_group,
        allergies
    ) VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
        COALESCE(NEW.raw_user_meta_data->>'phone', ''),
        'patient', -- Always force role to patient on public signups
        (NEW.raw_user_meta_data->>'age')::INTEGER,
        COALESCE(NEW.raw_user_meta_data->>'gender', 'Male'),
        COALESCE(NEW.raw_user_meta_data->>'blood_group', 'B+'),
        COALESCE(NEW.raw_user_meta_data->>'allergies', 'None recorded')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================
-- 7. ONE-TIME MASTER ADMIN ACCOUNT CREATION
-- Credentials:
-- Email:    admin@medsageclinic.com
-- Password: MedSageAdmin2026!
-- ====================================================================
DO $$
DECLARE
    admin_uid UUID;
    existing_admin_count INT;
BEGIN
    -- Check if any admin already exists
    SELECT COUNT(*) INTO existing_admin_count FROM public.profiles WHERE role = 'admin';
    
    IF existing_admin_count > 0 THEN
        RAISE NOTICE 'Master Administrator already exists. No action taken.';
    ELSE
        -- Generate new UUID for Admin
        admin_uid := gen_random_uuid();

        -- Insert into auth.users (Supabase authentication)
        INSERT INTO auth.users (
            instance_id,
            id,
            aud,
            role,
            email,
            encrypted_password,
            email_confirmed_at,
            raw_app_meta_data,
            raw_user_meta_data,
            created_at,
            updated_at
        ) VALUES (
            '00000000-0000-0000-0000-000000000000',
            admin_uid,
            'authenticated',
            'authenticated',
            'admin@medsageclinic.com',
            crypt('MedSageAdmin2026!', gen_salt('bf')),
            NOW(),
            '{"provider":"email","providers":["email"]}'::jsonb,
            '{"full_name":"Dr. Ahmad Khan (Chief Medical Officer)"}'::jsonb,
            NOW(),
            NOW()
        );

        -- Insert into public.profiles with role = 'admin'
        INSERT INTO public.profiles (
            id,
            email,
            full_name,
            phone,
            role,
            age,
            gender,
            blood_group
        ) VALUES (
            admin_uid,
            'admin@medsageclinic.com',
            'Dr. Ahmad Khan (Chief Medical Officer)',
            '+92 300 1234567',
            'admin',
            42,
            'Male',
            'O+'
        );

        RAISE NOTICE 'Master Administrator account successfully initialized for admin@medsageclinic.com!';
    END IF;
END $$;

-- ====================================================================
-- 8. SAMPLE PATIENT & CHECKUP SEED DATA (For Immediate Demonstration)
-- ====================================================================
DO $$
DECLARE
    patient1_uid UUID := '11111111-1111-1111-1111-111111111111';
    patient2_uid UUID := '22222222-2222-2222-2222-222222222222';
BEGIN
    -- Seed demo patient 1 (Fatima Ali)
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'fatima.ali@example.com') THEN
        INSERT INTO auth.users (
            instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
            raw_app_meta_data, raw_user_meta_data, created_at, updated_at
        ) VALUES (
            '00000000-0000-0000-0000-000000000000', patient1_uid, 'authenticated', 'authenticated',
            'fatima.ali@example.com', crypt('Patient123!', gen_salt('bf')), NOW(),
            '{"provider":"email","providers":["email"]}'::jsonb,
            '{"full_name":"Fatima Ali","phone":"+92 321 4567890"}'::jsonb, NOW(), NOW()
        );

        INSERT INTO public.profiles (id, email, full_name, phone, role, age, gender, blood_group, allergies)
        VALUES (patient1_uid, 'fatima.ali@example.com', 'Fatima Ali', '+92 321 4567890', 'patient', 28, 'Female', 'B+', 'Penicillin')
        ON CONFLICT (id) DO NOTHING;
    END IF;

    -- Seed demo patient 2 (Usman Raza)
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE email = 'usman.raza@example.com') THEN
        INSERT INTO auth.users (
            instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
            raw_app_meta_data, raw_user_meta_data, created_at, updated_at
        ) VALUES (
            '00000000-0000-0000-0000-000000000000', patient2_uid, 'authenticated', 'authenticated',
            'usman.raza@example.com', crypt('Patient123!', gen_salt('bf')), NOW(),
            '{"provider":"email","providers":["email"]}'::jsonb,
            '{"full_name":"Usman Raza","phone":"+92 333 9876543"}'::jsonb, NOW(), NOW()
        );

        INSERT INTO public.profiles (id, email, full_name, phone, role, age, gender, blood_group, allergies)
        VALUES (patient2_uid, 'usman.raza@example.com', 'Usman Raza', '+92 333 9876543', 'patient', 35, 'Male', 'O+', 'None')
        ON CONFLICT (id) DO NOTHING;
    END IF;

    -- Seed sample appointments
    INSERT INTO public.appointments (patient_id, full_name, phone, email, service, appointment_date, appointment_time, message, status)
    VALUES 
    (patient1_uid, 'Fatima Ali', '+92 321 4567890', 'fatima.ali@example.com', 'General Physician', CURRENT_DATE, '11:30 AM', 'Regular follow-up for seasonal allergies and migraine', 'confirmed'),
    (patient2_uid, 'Usman Raza', '+92 333 9876543', 'usman.raza@example.com', 'Skin Treatment', CURRENT_DATE + INTERVAL '1 day', '03:00 PM', 'Eczema flare-up review and topical cream prescription', 'pending'),
    (NULL, 'Ayesha Malik', '+92 301 2233445', 'ayesha.m@example.com', 'Vaccination', CURRENT_DATE + INTERVAL '2 days', '10:00 AM', 'Flu vaccination for family members', 'pending')
    ON CONFLICT DO NOTHING;

    -- Seed checkups for Fatima Ali
    IF NOT EXISTS (SELECT 1 FROM public.checkups WHERE patient_id = patient1_uid) THEN
        INSERT INTO public.checkups (
            patient_id, doctor_name, checkup_date, diagnosis, symptoms, vitals, prescriptions, doctor_notes, follow_up_date
        ) VALUES 
        (
            patient1_uid,
            'Dr. Ahmad Khan',
            CURRENT_DATE - INTERVAL '14 days',
            'Acute Rhinosinusitis & Tension Headache',
            'Nasal congestion, facial pressure, throbbing headache for 4 days',
            '{"bp": "118/76", "pulse": "74 bpm", "temp": "99.1°F", "weight": "58 kg"}'::jsonb,
            '[
                {"medicine": "Amoxicillin-Clavulanate 625mg", "dosage": "1 tablet", "frequency": "Twice daily (after meals)", "duration": "7 days"},
                {"medicine": "Fexofenadine 120mg", "dosage": "1 tablet", "frequency": "Once daily at bedtime", "duration": "10 days"},
                {"medicine": "Normal Saline Nasal Spray", "dosage": "2 sprays", "frequency": "3 times daily", "duration": "As needed"}
            ]'::jsonb,
            'Patient advised steam inhalation twice daily and adequate hydration. Avoid cold exposure.',
            CURRENT_DATE + INTERVAL '14 days'
        ),
        (
            patient1_uid,
            'Dr. Ahmad Khan',
            CURRENT_DATE - INTERVAL '45 days',
            'Routine Wellness & Iron Deficiency Anemia Screening',
            'Mild lethargy, fatigue on exertion',
            '{"bp": "115/72", "pulse": "78 bpm", "temp": "98.4°F", "weight": "57 kg"}'::jsonb,
            '[
                {"medicine": "Ferrous Fumarate + Folic Acid", "dosage": "1 capsule", "frequency": "Once daily with Vitamin C", "duration": "30 days"},
                {"medicine": "Vitamin D3 200,000 IU", "dosage": "1 ampoule", "frequency": "Monthly for 3 months", "duration": "3 months"}
            ]'::jsonb,
            'Hemoglobin was 10.8 g/dL. Recommended diet rich in green leafy vegetables, dates, and pomegranate.',
            CURRENT_DATE - INTERVAL '15 days'
        );
    END IF;

    -- Seed checkup for Usman Raza
    IF NOT EXISTS (SELECT 1 FROM public.checkups WHERE patient_id = patient2_uid) THEN
        INSERT INTO public.checkups (
            patient_id, doctor_name, checkup_date, diagnosis, symptoms, vitals, prescriptions, doctor_notes, follow_up_date
        ) VALUES 
        (
            patient2_uid,
            'Dr. Ahmad Khan',
            CURRENT_DATE - INTERVAL '21 days',
            'Atopic Dermatitis (Chronic Eczema) Flare-up',
            'Severe pruritus, erythema, and xerosis on both antecubital fossae',
            '{"bp": "128/82", "pulse": "70 bpm", "temp": "98.6°F", "weight": "76 kg"}'::jsonb,
            '[
                {"medicine": "Hydrocortisone 1% Cream", "dosage": "Apply thin layer", "frequency": "Twice daily on affected patches", "duration": "10 days"},
                {"medicine": "Cetirizine 10mg", "dosage": "1 tablet", "frequency": "Once daily at night", "duration": "14 days"},
                {"medicine": "Liquid Paraffin Moisturizing Emollient", "dosage": "Generous application", "frequency": "Immediately after shower & as needed", "duration": "Continuous"}
            ]'::jsonb,
            'Advised to avoid synthetic fabrics, harsh soaps, and very hot water baths.',
            CURRENT_DATE + INTERVAL '7 days'
        );
    END IF;

END $$;
